name: walmart-time-series
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - pytest
  - mlflow
  - pytorch::pytorch
  - pytorch::torchvision
  - pip
  - pip:
    - -r requirements.txt